export type HitoTypographyRole = {
  className: string;
  description: string;
  id: string;
  inspectorSelectable?: boolean;
  label: string;
  match?: {
    fontFamilyIncludes: string;
    fontSizePx: number;
    fontWeight: string;
    letterSpacingPx?: number;
    lineHeightPx: number;
  };
  sample: string;
  spec: string;
  technicalDetails: string;
  use: string;
};

export const HITO_TYPOGRAPHY_ROLES: HitoTypographyRole[] = [
  {
    className: "hito-display-title",
    description: "Largest display heading used for hero-level product names.",
    id: "display-title",
    label: "Display title",
    sample: "A running plan that stays honest.",
    spec: "Fraunces · clamp(3.5rem, 7vw, 5rem) · 400 · -0.02em · lh 1",
    technicalDetails: "Fraunces · clamp(3.5rem, 7vw, 5rem) · 400 · lh 1 · -0.02em",
    use: "Rare editorial emphasis for auth or top-tier entry moments.",
  },
  {
    className: "hito-page-title",
    description: "Primary page title role.",
    id: "page-title",
    label: "Page title",
    sample: "Profile details that follow your training.",
    spec: "Fraunces · clamp(3rem, 6vw, 4.5rem) · 400 · -0.02em · lh 1",
    technicalDetails: "Fraunces · clamp(3rem, 6vw, 4.5rem) · 400 · lh 1 · -0.02em",
    use: "Top-level route title or major state heading.",
  },
  {
    className: "hito-modal-title",
    description: "Primary heading inside bounded product dialogs.",
    id: "modal-title",
    label: "Modal title",
    sample: "Edit schedule",
    spec: "Fraunces · 1.75-2rem · 400 · -0.02em · lh 1.1",
    technicalDetails: "Fraunces · clamp(1.75rem, 5vw, 2rem) · 400 · lh 1.1 · -0.02em",
    use: "Primary heading inside bounded product dialogs.",
  },
  {
    className: "hito-section-title",
    description: "Section-level title role.",
    id: "section-title",
    label: "Section title",
    sample: "Body data",
    spec: "Fraunces · 1.5rem · 400 · -0.02em · lh 1.15",
    technicalDetails: "Fraunces · 1.5rem · 400 · lh 1.15 · -0.02em",
    use: "Section-level orientation within an open surface.",
  },
  {
    className: "hito-panel-title",
    description: "Compact panel or card title role.",
    id: "panel-title",
    label: "Panel title",
    sample: "Plan vs run",
    spec: "Fraunces · 1.25-1.375rem · 400 · -0.015em · lh 1.18",
    technicalDetails: "Fraunces · clamp(1.25rem, 3vw, 1.375rem) · 400 · lh 1.18 · -0.015em",
    use: "Compact internal panels, review modules, and feedback sections.",
  },
  {
    className: "hito-list-row-title",
    description: "Primary label inside list-row anatomy.",
    id: "list-row-title",
    label: "List row title",
    match: {
      fontFamilyIncludes: "Poppins",
      fontSizePx: 14,
      fontWeight: "400",
      lineHeightPx: 18.9,
    },
    sample: "Same typography, no click",
    spec: "Poppins · 0.875rem · 400 · lh 1.35",
    technicalDetails: "Poppins · 0.875rem · 400 · lh 1.35",
    use: "Primary label inside list rows and compact repeated row anatomy.",
  },
  {
    className: "hito-body",
    description: "Default body copy role.",
    id: "body",
    label: "Body",
    match: {
      fontFamilyIncludes: "Poppins",
      fontSizePx: 14,
      fontWeight: "400",
      lineHeightPx: 22.12,
    },
    sample: "This compares the planned workout with the uploaded run.",
    spec: "Poppins · 0.875rem · 400 · lh 1.58",
    technicalDetails: "Poppins · 0.875rem · 400 · lh 1.58",
    use: "Default readable paragraph for page, modal, and section support.",
  },
  {
    className: "hito-body-small",
    description: "Small supporting body copy role.",
    id: "body-small",
    label: "Body small",
    match: {
      fontFamilyIncludes: "Poppins",
      fontSizePx: 13,
      fontWeight: "400",
      lineHeightPx: 19.5,
    },
    sample: "Saved workout history stays preserved.",
    spec: "Poppins · 0.8125rem · 400 · lh 1.5",
    technicalDetails: "Poppins · 0.8125rem · 400 · lh 1.5",
    use: "Dense secondary explanations, row support, and metadata.",
  },
  {
    className: "hito-field-helper",
    description: "Field-adjacent helper copy role.",
    id: "helper",
    label: "Helper",
    match: {
      fontFamilyIncludes: "Poppins",
      fontSizePx: 12,
      fontWeight: "400",
      lineHeightPx: 17.4,
    },
    sample: "Nothing changes until you choose Apply update.",
    spec: "Poppins · 0.75rem · 400 · lh 1.45",
    technicalDetails: "Poppins · 0.75rem · 400 · lh 1.45",
    use: "Field-adjacent or control-adjacent operational guidance.",
  },
  {
    className: "hito-caption",
    description: "Quiet caption and secondary metadata role.",
    id: "caption",
    label: "Caption",
    match: {
      fontFamilyIncludes: "Poppins",
      fontSizePx: 11,
      fontWeight: "400",
      lineHeightPx: 15.95,
    },
    sample: "Extracted activity: morning-run.fit",
    spec: "Poppins · 0.6875rem · 400 · lh 1.45",
    technicalDetails: "Poppins · 0.6875rem · 400 · lh 1.45",
    use: "Tertiary detail, legends, tiny footnotes, and timestamps.",
  },
  {
    className: "hito-label",
    description: "Compact field or metadata label role.",
    id: "label",
    label: "Label",
    sample: "Current plan",
    spec: "Poppins · 0.75rem · 600 · 0.01em · normal case · lh 1.25",
    technicalDetails: "Poppins · 0.75rem · 600 · lh 1.25 · 0.01em",
    use: "Micro orientation, never a substitute for a heading.",
  },
  {
    className: "hito-form-label",
    description: "Explicit ownership label for fields and controls.",
    id: "form-label",
    label: "Form label",
    sample: "Start training",
    spec: "Poppins · 0.75rem · 600 · 0.01em · normal case · lh 1.25",
    technicalDetails: "Poppins · 0.75rem · 600 · lh 1.25 · 0.01em",
    use: "Explicit ownership label for fields and controls.",
  },
  {
    className: "hito-micro-label",
    description: "Tiny uppercase route chrome and compact status metadata.",
    id: "micro-label",
    label: "Micro label",
    sample: "Saved mode",
    spec: "Poppins · 0.6875rem · 500 · 0.18em · uppercase · lh 1.2",
    technicalDetails: "Poppins · 0.6875rem · 500 · lh 1.2 · 0.18em",
    use: "Tiny uppercase route chrome and compact status metadata, not ordinary shell labels.",
  },
  {
    className: "hito-technical-mono",
    description: "Technical monospace readback role.",
    id: "technical-mono",
    label: "Technical mono",
    match: {
      fontFamilyIncludes: "JetBrains",
      fontSizePx: 12,
      fontWeight: "400",
      lineHeightPx: 17.4,
    },
    sample: "training-plan-v2",
    spec: "JetBrains Mono · 0.75rem · tabular nums · lh 1.45",
    technicalDetails: "JetBrains Mono · 0.75rem · 400 · lh 1.45",
    use: "Measured or fixed-format truth only.",
  },
  {
    className: "hito-button hito-button-secondary hito-button-sm",
    description: "Action text tuned by shared Hito button size tiers.",
    id: "button",
    inspectorSelectable: false,
    label: "Button",
    sample: "Generate proposal",
    spec: "Poppins · tiered 0.6875-0.9375rem · 500 · lh 1",
    technicalDetails: "Poppins · tiered 0.6875-0.9375rem · 500 · lh 1",
    use: "Action text tuned by shared Hito button size tiers.",
  },
  {
    className: "hito-menu-text",
    description: "Shell navigation, dropdown rows, and utility menu text.",
    id: "nav-menu",
    inspectorSelectable: false,
    label: "Nav / menu",
    sample: "User settings",
    spec: "Poppins · 0.8125-0.875rem · 500 · lh 1-1.3",
    technicalDetails: "Poppins · 0.8125-0.875rem · 500 · lh 1-1.3",
    use: "Shell navigation, dropdown rows, and utility menu text.",
  },
  {
    className: "hito-metric-value",
    description: "Measured truth value role.",
    id: "metric",
    inspectorSelectable: false,
    label: "Metric",
    sample: "42.2 km",
    spec: "JetBrains Mono · 1rem · 500 · tabular · lh 1.1",
    technicalDetails: "JetBrains Mono · 1rem · 500 · tabular · lh 1.1",
    use: "Measured truth: distance, duration, pace, counts, and dates.",
  },
  {
    className: "hito-status-pill",
    description: "Semantic state identifier role.",
    id: "status",
    inspectorSelectable: false,
    label: "Status",
    sample: "Ready",
    spec: "Poppins · 0.625rem · 500 · normal case · rounded rectangle",
    technicalDetails: "Poppins · 0.625rem · 500 · normal case",
    use: "Semantic state identifier, never a heading.",
  },
  {
    className: "hito-field-success",
    description: "Bounded action feedback near controls.",
    id: "error-success",
    inspectorSelectable: false,
    label: "Error / success",
    sample: "User settings saved.",
    spec: "Poppins · 0.875rem · 500 · lh 1.45",
    technicalDetails: "Poppins · 0.875rem · 500 · lh 1.45",
    use: "Bounded action feedback near the relevant control family.",
  },
];

export const HITO_INSPECTOR_TYPOGRAPHY_ROLES = HITO_TYPOGRAPHY_ROLES.filter(
  (role) => role.inspectorSelectable !== false,
);
