export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      runner_profiles: {
        Row: {
          user_id: string;
          goal_type: "build_consistency" | "first_race" | "distance_build";
          goal_label: string;
          baseline_sessions_per_week: number;
          baseline_long_run_km: number;
          baseline_notes: string | null;
          setup_state: "completed";
          setup_completed_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          goal_type: "build_consistency" | "first_race" | "distance_build";
          goal_label: string;
          baseline_sessions_per_week: number;
          baseline_long_run_km: number;
          baseline_notes?: string | null;
          setup_state?: "completed";
          setup_completed_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["runner_profiles"]["Insert"]>;
      };
      plan_cycles: {
        Row: {
          id: string;
          user_id: string;
          status: "active" | "archived";
          title: string;
          goal_summary: string;
          source_template: string;
          schema_version: string;
          source_kind: string | null;
          start_date: string;
          end_date: string;
          target_date: string | null;
          goal_metadata: Json | null;
          plan_preferences: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          status?: "active" | "archived";
          title: string;
          goal_summary: string;
          source_template: string;
          schema_version?: string;
          source_kind?: string | null;
          start_date: string;
          end_date: string;
          target_date?: string | null;
          goal_metadata?: Json | null;
          plan_preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["plan_cycles"]["Insert"]>;
      };
      planned_workouts: {
        Row: {
          id: string;
          plan_cycle_id: string;
          user_id: string;
          workout_date: string;
          weekday: string;
          week_number: number;
          phase: string;
          workout_type: "easy" | "steady_or_easy" | "rest" | "long_run" | "quality";
          source_workout_id: string | null;
          source_workout_type: string | null;
          title: string;
          notes: string | null;
          planned_rpe: number | null;
          estimated_fatigue: string | null;
          recovery_priority: string | null;
          steps: Json;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          plan_cycle_id: string;
          user_id: string;
          workout_date: string;
          weekday: string;
          week_number: number;
          phase: string;
          workout_type: "easy" | "steady_or_easy" | "rest" | "long_run" | "quality";
          source_workout_id?: string | null;
          source_workout_type?: string | null;
          title: string;
          notes?: string | null;
          planned_rpe?: number | null;
          estimated_fatigue?: string | null;
          recovery_priority?: string | null;
          steps: Json;
          display_order: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["planned_workouts"]["Insert"]>;
      };
      workout_logs: {
        Row: {
          id: string;
          planned_workout_id: string;
          user_id: string;
          outcome: "completed" | "partial" | "skipped";
          actual_distance_km: number | null;
          actual_duration_min: number | null;
          rpe: number | null;
          notes: string | null;
          intervals_completed: number | null;
          logged_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          planned_workout_id: string;
          user_id?: string;
          outcome: "completed" | "partial" | "skipped";
          actual_distance_km?: number | null;
          actual_duration_min?: number | null;
          rpe?: number | null;
          notes?: string | null;
          intervals_completed?: number | null;
          logged_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workout_logs"]["Insert"]>;
      };
      workout_result_assets: {
        Row: {
          id: string;
          user_id: string;
          planned_workout_id: string;
          workout_log_id: string | null;
          asset_kind: "garmin_fit" | "garmin_zip";
          storage_bucket: string;
          storage_path: string;
          original_file_name: string;
          mime_type: string;
          file_size_bytes: number;
          parse_status: "uploaded" | "extracted" | "parsed" | "failed";
          primary_file_kind: "fit" | null;
          primary_file_name: string | null;
          parse_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          planned_workout_id: string;
          workout_log_id?: string | null;
          asset_kind: "garmin_fit" | "garmin_zip";
          storage_bucket: string;
          storage_path: string;
          original_file_name: string;
          mime_type: string;
          file_size_bytes: number;
          parse_status: "uploaded" | "extracted" | "parsed" | "failed";
          primary_file_kind?: "fit" | null;
          primary_file_name?: string | null;
          parse_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workout_result_assets"]["Insert"]>;
      };
      workout_actual_metrics: {
        Row: {
          id: string;
          user_id: string;
          planned_workout_id: string;
          workout_log_id: string | null;
          result_asset_id: string;
          source_kind: "garmin_fit";
          status: "normalized" | "reviewed" | "superseded";
          activity_started_at: string | null;
          activity_local_date: string | null;
          actual_duration_min: number | null;
          actual_distance_km: number | null;
          actual_avg_hr: number | null;
          actual_max_hr: number | null;
          actual_avg_power: number | null;
          actual_max_power: number | null;
          actual_avg_cadence: number | null;
          actual_calories: number | null;
          actual_elevation_gain_m: number | null;
          actual_elevation_loss_m: number | null;
          actual_interval_count: number | null;
          actual_step_payload: Json | null;
          lap_payload: Json | null;
          summary_payload: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          planned_workout_id: string;
          workout_log_id?: string | null;
          result_asset_id: string;
          source_kind: "garmin_fit";
          status?: "normalized" | "reviewed" | "superseded";
          activity_started_at?: string | null;
          activity_local_date?: string | null;
          actual_duration_min?: number | null;
          actual_distance_km?: number | null;
          actual_avg_hr?: number | null;
          actual_max_hr?: number | null;
          actual_avg_power?: number | null;
          actual_max_power?: number | null;
          actual_avg_cadence?: number | null;
          actual_calories?: number | null;
          actual_elevation_gain_m?: number | null;
          actual_elevation_loss_m?: number | null;
          actual_interval_count?: number | null;
          actual_step_payload?: Json | null;
          lap_payload?: Json | null;
          summary_payload: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workout_actual_metrics"]["Insert"]>;
      };
      workout_comparisons: {
        Row: {
          id: string;
          user_id: string;
          planned_workout_id: string;
          actual_metrics_id: string;
          comparison_status: "complete" | "partial" | "insufficient_data";
          completion_state: "matched" | "partially_matched" | "unclear";
          difference_payload: Json;
          comparison_confidence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          planned_workout_id: string;
          actual_metrics_id: string;
          comparison_status: "complete" | "partial" | "insufficient_data";
          completion_state: "matched" | "partially_matched" | "unclear";
          difference_payload: Json;
          comparison_confidence: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workout_comparisons"]["Insert"]>;
      };
      workout_ai_insights: {
        Row: {
          id: string;
          user_id: string;
          planned_workout_id: string;
          actual_metrics_id: string;
          comparison_id: string;
          model: string;
          response_id: string | null;
          status: "final" | "superseded";
          analysis_summary: string;
          difference_explanation: string;
          next_workout_recommendation: string;
          recommendation_level: "keep" | "soft_adjust" | "review";
          caution_flags: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          planned_workout_id: string;
          actual_metrics_id: string;
          comparison_id: string;
          model: string;
          response_id?: string | null;
          status: "final" | "superseded";
          analysis_summary: string;
          difference_explanation: string;
          next_workout_recommendation: string;
          recommendation_level: "keep" | "soft_adjust" | "review";
          caution_flags?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workout_ai_insights"]["Insert"]>;
      };
    };
  };
}
