export {
  createEmptyManualActivePlan,
  createEmptyManualActivePlanForUser,
  confirmWorkoutCommandAction,
  confirmWorkoutCommandForUser,
  initializeWorkoutDocument,
  initializeWorkoutDocumentAction,
  initializeWorkoutDocumentForUser,
  reviewWorkoutCommandAction,
  reviewWorkoutCommandForUser,
  type WorkoutDocumentInitializerResult,
  type WorkoutDocumentInitializerDependencies,
  type WorkoutCommandConfirmationResult,
} from "@/lib/manual-workout-authoring/actions";
export type { ManualWorkoutMoveTargetDayKind } from "@/lib/manual-workout-authoring/move-workout";
export {
  confirmWorkoutDocumentPersistedEditForUser,
  reviewWorkoutDocumentPersistedEditForUser,
  type WorkoutDocumentPersistedEditConfirmResult,
  type WorkoutDocumentPersistedEditDependencies,
  type WorkoutDocumentPersistedEditFailureReason,
  type WorkoutDocumentPersistedEditReviewResult,
} from "@/lib/manual-workout-authoring/edit-workout";
export {
  deleteManualWorkoutSavedTemplate,
  deleteManualWorkoutSavedTemplateForUser,
  listManualWorkoutSavedTemplatesForUser,
  manualWorkoutSavedTemplateDeleteInputSchema,
  type ManualWorkoutSavedTemplateDependencies,
  type ManualWorkoutSavedTemplateDeleteResult,
  type ManualWorkoutSavedTemplateFailureReason,
  type ManualWorkoutSavedTemplateListResult,
  type ManualWorkoutSavedTemplateRepository,
  type ManualWorkoutSavedTemplateView,
} from "@/lib/manual-workout-authoring/saved-templates";
export {
  MANUAL_WORKOUT_TEMPLATE_CATALOG_SOURCE_KIND,
  hideManualWorkoutBuiltInTemplate,
  listManualWorkoutTemplateCatalog,
  listManualWorkoutTemplateCatalogForUser,
  restoreAllManualWorkoutBuiltInTemplates,
  restoreAllManualWorkoutBuiltInTemplatesForUser,
  restoreManualWorkoutBuiltInTemplate,
  updateManualWorkoutBuiltInVisibilityForUser,
  type ManualWorkoutTemplateCatalogDependencies,
  type ManualWorkoutTemplateCatalogResult,
  type ManualWorkoutTemplateVisibilityRepository,
  type ManualWorkoutTemplateVisibilityResult,
} from "@/lib/manual-workout-authoring/template-catalog";
export {
  getManualWorkoutTemplate,
  listSupportedManualWorkoutTemplates,
  listVisibleManualWorkoutStarterTemplates,
  listManualWorkoutTemplates,
  INTERNAL_SUPPORTED_MANUAL_WORKOUT_TEMPLATE_KEYS,
  MANUAL_WORKOUT_TEMPLATE_MAPPING_GAPS,
  MANUAL_WORKOUT_TEMPLATE_REGISTRY,
  VISIBLE_MANUAL_WORKOUT_STARTER_TEMPLATE_KEYS,
  type ManualWorkoutTemplate,
} from "@/lib/manual-workout-authoring/templates";
export {
  MANUAL_WORKOUT_AUTHORING_SOURCE_KIND,
  MANUAL_WORKOUT_AUTHORING_SOURCE_STATUS,
  MANUAL_USER_BUILT_PLAN_SOURCE_KIND,
  MANUAL_USER_BUILT_PLAN_SOURCE_STATUS,
  MANUAL_EMPTY_PLAN_SETUP_PAYLOAD_VERSION,
  MANUAL_SETUP_RUNNING_LEVEL_VALUES,
  MANUAL_WORKOUT_REVIEW_PAYLOAD_VERSION,
  MANUAL_WORKOUT_TARGET_TRUTH_MODE_VALUES,
  MANUAL_WORKOUT_TEMPLATE_KEY_VALUES,
  manualEmptyPlanSetupInputSchema,
  type ManualEmptyPlanCreateFailureReason,
  type ManualEmptyPlanCreateResult,
  type ManualEmptyPlanSetupInput,
  type ManualSetupRunningLevel,
  type ManualWorkoutReviewMetadata,
  type ManualWorkoutTargetTruthMode,
  type ManualWorkoutTemplateKey,
} from "@/lib/manual-workout-authoring/schema";
export {
  WORKOUT_COMMAND_REVIEW_PAYLOAD_VERSION,
  WORKOUT_COMMAND_SAVED_TEMPLATE_PAYLOAD_VERSION,
  type ReviewedWorkoutCommandCandidate,
  type WorkoutCommand,
  type WorkoutCommandCollision,
  type WorkoutCommandInput,
  type WorkoutCommandMoveExpectedFingerprints,
  type WorkoutCommandMoveTargetPolicy,
  type WorkoutCommandReviewIssue,
  type WorkoutCommandReviewResult,
} from "@/lib/workout-authoring-review";
