export {
  addManualWorkoutToActivePlan,
  addManualWorkoutToActivePlanForUser,
  buildManualWorkoutReviewExactnessPayload,
  createEmptyManualActivePlan,
  createEmptyManualActivePlanForUser,
  reviewManualWorkoutDraft,
  validateManualWorkoutReviewExactness,
} from "@/lib/manual-workout-authoring/actions";
export {
  copyManualWorkoutWithinActivePlan,
  copyManualWorkoutWithinActivePlanForUser,
  confirmManualWorkoutCopyPasteDraft,
  confirmManualWorkoutCopyPasteDraftForUser,
  manualWorkoutCopyPasteConfirmInputSchema,
  manualWorkoutDirectCopyInputSchema,
  manualWorkoutCopyPasteReviewInputSchema,
  reviewManualWorkoutCopyPasteDraft,
  reviewManualWorkoutCopyPasteDraftForUser,
  type ManualWorkoutCopyPasteConfirmResult,
  type ManualWorkoutCopyPasteDependencies,
  type ManualWorkoutCopyPasteFailureReason,
  type ManualWorkoutCopyPasteReviewResult,
  type ManualWorkoutDirectCopyResult,
} from "@/lib/manual-workout-authoring/copy-paste";
export {
  confirmManualWorkoutDeleteClear,
  confirmManualWorkoutDeleteClearForUser,
  manualWorkoutDeleteClearConfirmInputSchema,
  manualWorkoutDeleteClearReviewInputSchema,
  reviewManualWorkoutDeleteClear,
  reviewManualWorkoutDeleteClearForUser,
  type ManualWorkoutDeleteClearConfirmResult,
  type ManualWorkoutDeleteClearDependencies,
  type ManualWorkoutDeleteClearFailureReason,
  type ManualWorkoutDeleteClearReviewResult,
} from "@/lib/manual-workout-authoring/delete-clear";
export {
  confirmManualWorkoutMove,
  confirmManualWorkoutMoveForUser,
  manualWorkoutDirectMoveInputSchema,
  manualWorkoutMoveConfirmInputSchema,
  manualWorkoutMoveReviewInputSchema,
  moveManualWorkoutWithinActivePlan,
  moveManualWorkoutWithinActivePlanForUser,
  reviewManualWorkoutMove,
  reviewManualWorkoutMoveForUser,
  type ManualWorkoutDirectMoveResult,
  type ManualWorkoutMoveConfirmResult,
  type ManualWorkoutMoveDependencies,
  type ManualWorkoutMoveFailureReason,
  type ManualWorkoutMoveReplacementTarget,
  type ManualWorkoutMoveReviewResult,
  type ManualWorkoutMoveTargetDayKind,
} from "@/lib/manual-workout-authoring/move-workout";
export {
  confirmManualWorkoutPersistedEdit,
  confirmManualWorkoutPersistedEditForUser,
  manualWorkoutPersistedEditConfirmInputSchema,
  manualWorkoutPersistedEditReviewInputSchema,
  reconstructManualWorkoutPersistedEditDraft,
  reconstructManualWorkoutPersistedEditDraftForUser,
  reviewManualWorkoutPersistedEditDraft,
  reviewManualWorkoutPersistedEditDraftForUser,
  type ManualWorkoutPersistedEditConfirmResult,
  type ManualWorkoutPersistedEditDependencies,
  type ManualWorkoutPersistedEditFailureReason,
  type ManualWorkoutPersistedEditReconstructResult,
  type ManualWorkoutPersistedEditReviewResult,
} from "@/lib/manual-workout-authoring/edit-workout";
export {
  MANUAL_SAVED_WORKOUT_TEMPLATE_PAYLOAD_VERSION,
  MANUAL_SAVED_WORKOUT_TEMPLATE_SOURCE_KIND,
  MANUAL_SAVED_WORKOUT_TEMPLATE_SOURCE_STATUS,
  MANUAL_WORKOUT_TEMPLATE_REGISTRY_VERSION,
  listManualWorkoutSavedTemplates,
  listManualWorkoutSavedTemplatesForUser,
  manualWorkoutSavedTemplateReviewInputSchema,
  manualWorkoutSavedTemplateSaveInputSchema,
  reviewManualWorkoutSavedTemplate,
  reviewManualWorkoutSavedTemplateForUser,
  saveManualWorkoutSavedTemplate,
  saveManualWorkoutSavedTemplateForUser,
  type ManualWorkoutSavedTemplateDependencies,
  type ManualWorkoutSavedTemplateFailureReason,
  type ManualWorkoutSavedTemplateListResult,
  type ManualWorkoutSavedTemplateReviewInput,
  type ManualWorkoutSavedTemplateReviewResult,
  type ManualWorkoutSavedTemplateRepository,
  type ManualWorkoutSavedTemplateSaveInput,
  type ManualWorkoutSavedTemplateSaveResult,
  type ManualWorkoutSavedTemplateView,
} from "@/lib/manual-workout-authoring/saved-templates";
export { buildManualWorkoutUserBuiltTrainingPlan } from "@/lib/manual-workout-authoring/persistence";
export {
  getManualWorkoutTemplate,
  listSupportedManualWorkoutTemplates,
  listVisibleManualWorkoutStarterTemplates,
  listManualWorkoutTemplates,
  INTERNAL_SUPPORTED_MANUAL_WORKOUT_TEMPLATE_KEYS,
  MANUAL_WORKOUT_TEMPLATE_MAPPING_GAPS,
  MANUAL_WORKOUT_TEMPLATE_REGISTRY,
  VISIBLE_MANUAL_WORKOUT_STARTER_TEMPLATE_KEYS,
  type ManualWorkoutTemplate,
} from "@/lib/manual-workout-authoring/templates";
export {
  MANUAL_WORKOUT_AUTHORING_SOURCE_KIND,
  MANUAL_WORKOUT_AUTHORING_SOURCE_STATUS,
  MANUAL_USER_BUILT_PLAN_SOURCE_KIND,
  MANUAL_USER_BUILT_PLAN_SOURCE_STATUS,
  MANUAL_EMPTY_PLAN_SETUP_PAYLOAD_VERSION,
  MANUAL_SETUP_RUNNING_LEVEL_VALUES,
  MANUAL_WORKOUT_REVIEW_PAYLOAD_VERSION,
  MANUAL_WORKOUT_BLOCK_KEY_VALUES,
  MANUAL_WORKOUT_REPEAT_SAFETY_KIND_VALUES,
  MANUAL_WORKOUT_TARGET_TRUTH_MODE_VALUES,
  MANUAL_WORKOUT_TARGET_SOURCE_VALUES,
  MANUAL_WORKOUT_TEMPLATE_KEY_VALUES,
  manualWorkoutAddToActivePlanInputSchema,
  manualEmptyPlanSetupInputSchema,
  manualWorkoutDraftInputSchema,
  type ManualEmptyPlanCreateFailureReason,
  type ManualEmptyPlanCreateResult,
  type ManualEmptyPlanSetupInput,
  type ManualSetupRunningLevel,
  type ManualWorkoutAddToActivePlanFailureReason,
  type ManualWorkoutAddToActivePlanInput,
  type ManualWorkoutAddToActivePlanResult,
  type ManualWorkoutBlockInput,
  type ManualWorkoutCanonicalDraft,
  type ManualWorkoutConstructorEntryInput,
  type ManualWorkoutDraftConflict,
  type ManualWorkoutDraftContext,
  type ManualWorkoutDraftInput,
  type ManualWorkoutDraftIssue,
  type ManualWorkoutDraftReviewResult,
  type ManualWorkoutRepeatGroupInput,
  type ManualWorkoutRepeatSafetyKind,
  type ManualWorkoutReviewExactnessFailureReason,
  type ManualWorkoutReviewSummary,
  type ManualWorkoutTargetSource,
  type ManualWorkoutTargetTruthMode,
  type ManualWorkoutTemplateKey,
} from "@/lib/manual-workout-authoring/schema";
