import type { RunningPlanScenarioRule } from "@/lib/plan-creation-engine/source-types";

export const scenarioRules: readonly RunningPlanScenarioRule[] = [
  {
    family: "10K",
    runnerLevel: "beginner_new_runner",
    daysPerWeek: [3],
    goalPromise: "Complete 10K safely.",
    weeklyRhythm: "Mostly easy plus one light development touch some weeks.",
    longRunShape: "Small progressive long run with frequent cutbacks.",
    endpointRule: "Explicit 10K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No support-only endpoint.",
  },
  {
    family: "10K",
    runnerLevel: "sometimes_runs",
    daysPerWeek: [3, 4],
    goalPromise: "Complete 10K with visible growth.",
    weeklyRhythm: "Easy/recovery backbone plus one moderate touch maximum.",
    longRunShape: "Clear long-run growth with cutbacks.",
    endpointRule: "Explicit 10K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No generic final long run.",
  },
  {
    family: "10K",
    runnerLevel: "runs_a_lot",
    daysPerWeek: [4, 5],
    goalPromise: "Complete 10K with clearer 10K specificity.",
    weeklyRhythm: "One quality touch maximum plus strong support stack.",
    longRunShape: "Stronger but still bounded long-run growth.",
    endpointRule: "Explicit 10K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No vague final week.",
  },
  {
    family: "10K",
    runnerLevel: "professional_competitive",
    daysPerWeek: [4, 5],
    goalPromise: "Conservative 10K base only.",
    weeklyRhythm: "One quality touch maximum, not a sharp race block.",
    longRunShape: "Maintained long-run rhythm.",
    endpointRule: "Explicit 10K checkpoint or completion marker.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No advanced race-peak simulation.",
  },
  {
    family: "Half Marathon",
    runnerLevel: "beginner_new_runner",
    daysPerWeek: [3, 4, 5],
    goalPromise: "Auto-extended beginner bridge to an exact Half Marathon endpoint.",
    weeklyRhythm:
      "Run-walk/easy adaptation, light turnover, soft durability, and long-run-led growth.",
    longRunShape:
      "Progressive durability long runs with frequent cutbacks and varied checkpoint intent.",
    endpointRule: "Exact 21100m Half Marathon endpoint after the extended bridge.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No runner-level block, no hard intervals, and no compressed Half shortcut.",
  },
  {
    family: "Half Marathon",
    runnerLevel: "sometimes_runs",
    daysPerWeek: [3, 4],
    goalPromise: "Complete Half with visible specific development.",
    weeklyRhythm: "Easy/steady plus one moderate touch maximum.",
    longRunShape: "Clear long-run progression, cutbacks, occasional specific finish.",
    endpointRule: "Explicit 21.1K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No rest-day ending.",
  },
  {
    family: "Half Marathon",
    runnerLevel: "runs_a_lot",
    daysPerWeek: [4, 5],
    goalPromise: "Complete Half with stronger half-specific rhythm.",
    weeklyRhythm: "One moderate or threshold-like touch maximum.",
    longRunShape: "Long-run growth plus selective specific finish.",
    endpointRule: "Explicit 21.1K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No generic support-only last week.",
  },
  {
    family: "Half Marathon",
    runnerLevel: "professional_competitive",
    daysPerWeek: [4, 5],
    goalPromise: "Conservative Half base only unless a future advanced track exists.",
    weeklyRhythm: "One quality touch maximum only.",
    longRunShape: "Durable long-run rhythm.",
    endpointRule: "Explicit 21.1K checkpoint or completion marker.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No pseudo-elite race block.",
  },
  {
    family: "Marathon Completion",
    runnerLevel: "beginner_new_runner",
    daysPerWeek: [3, 4, 5],
    goalPromise: "Long finish-focused bridge to exact 42195m completion.",
    weeklyRhythm:
      "Run-walk/easy adaptation, recovery protection, light turnover, late steady support.",
    longRunShape:
      "Very patient long-run durability with repeated cutbacks, taper, and exact endpoint.",
    endpointRule: "Exact 42195m Marathon Completion endpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No intervals, no target-time pace, and no hidden base endpoint.",
  },
  {
    family: "Marathon Completion",
    runnerLevel: "sometimes_runs",
    daysPerWeek: [3, 4, 5],
    goalPromise: "Finish-focused full-marathon preparation with conservative specificity.",
    weeklyRhythm:
      "Easy/recovery backbone plus steady/progression support and late controlled tempo.",
    longRunShape: "Long-run durability checkpoints with controlled steady-finish weeks.",
    endpointRule: "Exact 42195m Marathon Completion endpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No race-pace, interval, or threshold leakage.",
  },
  {
    family: "Marathon Completion",
    runnerLevel: "runs_a_lot",
    daysPerWeek: [3, 4, 5],
    goalPromise: "Richer full-marathon completion build without performance-marathon claims.",
    weeklyRhythm: "Regular steady/progression/controlled-tempo support with one touch maximum.",
    longRunShape: "Repeated durability and steady-finish long runs with cutback protection.",
    endpointRule: "Exact 42195m Marathon Completion endpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No two-quality weeks and no target-time readiness.",
  },
  {
    family: "Marathon Completion",
    runnerLevel: "professional_competitive",
    daysPerWeek: [3, 4, 5],
    goalPromise: "Strongest completion-family build, still not a performance marathon plan.",
    weeklyRhythm: "Richer steady/progression/controlled-tempo support without interval logic.",
    longRunShape: "Frequent durability and steady-finish roles before taper and endpoint.",
    endpointRule: "Exact 42195m Marathon Completion endpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No race-pace or second-hard-session behavior.",
  },
] as const;
