import type { RunningPlanScenarioRule } from "@/lib/plan-creation-engine/source-types";

export const scenarioRules: readonly RunningPlanScenarioRule[] = [
  {
    family: "10K",
    runnerLevel: "beginner_new_runner",
    daysPerWeek: [3],
    goalPromise: "Complete 10K safely.",
    weeklyRhythm: "Mostly easy plus one light development touch some weeks.",
    longRunShape: "Small progressive long run with frequent cutbacks.",
    endpointRule: "Explicit 10K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No support-only endpoint.",
  },
  {
    family: "10K",
    runnerLevel: "sometimes_runs",
    daysPerWeek: [3, 4],
    goalPromise: "Complete 10K with visible growth.",
    weeklyRhythm: "Easy/recovery backbone plus one moderate touch maximum.",
    longRunShape: "Clear long-run growth with cutbacks.",
    endpointRule: "Explicit 10K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No generic final long run.",
  },
  {
    family: "10K",
    runnerLevel: "runs_a_lot",
    daysPerWeek: [4, 5],
    goalPromise: "Complete 10K with clearer 10K specificity.",
    weeklyRhythm: "One quality touch maximum plus strong support stack.",
    longRunShape: "Stronger but still bounded long-run growth.",
    endpointRule: "Explicit 10K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No vague final week.",
  },
  {
    family: "10K",
    runnerLevel: "professional_competitive",
    daysPerWeek: [4, 5],
    goalPromise: "Conservative 10K base only.",
    weeklyRhythm: "One quality touch maximum, not a sharp race block.",
    longRunShape: "Maintained long-run rhythm.",
    endpointRule: "Explicit 10K checkpoint or completion marker.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No advanced race-peak simulation.",
  },
  {
    family: "Half Marathon",
    runnerLevel: "beginner_new_runner",
    daysPerWeek: [3],
    goalPromise: "Conservative completion build if product allows the fit.",
    weeklyRhythm: "Easy/steady dominant with very careful specificity.",
    longRunShape: "Long-run emphasis and conservative growth.",
    endpointRule: "Explicit 21.1K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No readiness-only endpoint.",
  },
  {
    family: "Half Marathon",
    runnerLevel: "sometimes_runs",
    daysPerWeek: [3, 4],
    goalPromise: "Complete Half with visible specific development.",
    weeklyRhythm: "Easy/steady plus one moderate touch maximum.",
    longRunShape: "Clear long-run progression, cutbacks, occasional specific finish.",
    endpointRule: "Explicit 21.1K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No rest-day ending.",
  },
  {
    family: "Half Marathon",
    runnerLevel: "runs_a_lot",
    daysPerWeek: [4, 5],
    goalPromise: "Complete Half with stronger half-specific rhythm.",
    weeklyRhythm: "One moderate or threshold-like touch maximum.",
    longRunShape: "Long-run growth plus selective specific finish.",
    endpointRule: "Explicit 21.1K completion or checkpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No generic support-only last week.",
  },
  {
    family: "Half Marathon",
    runnerLevel: "professional_competitive",
    daysPerWeek: [4, 5],
    goalPromise: "Conservative Half base only unless a future advanced track exists.",
    weeklyRhythm: "One quality touch maximum only.",
    longRunShape: "Durable long-run rhythm.",
    endpointRule: "Explicit 21.1K checkpoint or completion marker.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No pseudo-elite race block.",
  },
  {
    family: "Marathon Base",
    runnerLevel: "beginner_new_runner",
    daysPerWeek: [4],
    goalPromise: "Base-building only if product keeps the promise honest.",
    weeklyRhythm: "Support-heavy with no aggressive specificity.",
    longRunShape: "Slow long-run progression with frequent cutbacks.",
    endpointRule: "Explicit base endpoint, not race endpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No fake marathon readiness.",
  },
  {
    family: "Marathon Base",
    runnerLevel: "sometimes_runs",
    daysPerWeek: [4, 5],
    goalPromise: "Honest base-building.",
    weeklyRhythm: "Easy/recovery dominance plus one specific touch maximum.",
    longRunShape: "Stronger long-run growth with cutbacks.",
    endpointRule: "Explicit base endpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No race-peak language.",
  },
  {
    family: "Marathon Base",
    runnerLevel: "runs_a_lot",
    daysPerWeek: [4, 5],
    goalPromise: "Durable marathon base.",
    weeklyRhythm: "One specific touch maximum or long-run specific finish, not both hard.",
    longRunShape: "Strong long-run progression with visible cutbacks.",
    endpointRule: "Explicit base endpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No endpoint overclaim.",
  },
  {
    family: "Marathon Base",
    runnerLevel: "professional_competitive",
    daysPerWeek: [4, 5],
    goalPromise: "Conservative base only, not full marathon prep.",
    weeklyRhythm: "One touch maximum with strong recovery protection.",
    longRunShape: "High but bounded durability block.",
    endpointRule: "Explicit base endpoint.",
    metricModeBias: "structure_first_editable_default_hr_optional",
    qualityGateFocus: "No full-race implication.",
  },
] as const;
