/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HubRouteImport } from './routes/hub'
import { Route as HitoDSRouteImport } from './routes/hitoDS'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BodyRouteImport } from './routes/body'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutDateRouteImport } from './routes/workout.$date'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCaptureRouteImport } from './routes/admin.capture'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiWorkoutResultUploadRouteImport } from './routes/api.workout-result.upload'
import { Route as ApiWorkoutResultRemoveRouteImport } from './routes/api.workout-result.remove'
import { Route as ApiProfileAvatarUploadRouteImport } from './routes/api.profile-avatar.upload'
import { Route as ApiPlanExportRouteImport } from './routes/api.plan.export'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLocalLoginRouteImport } from './routes/api.auth.local-login'
import { Route as ApiAuthConfirmRouteImport } from './routes/api.auth.confirm'
import { Route as ApiAdminAuthLoginRouteImport } from './routes/api.admin.auth.login'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const HitoDSRoute = HitoDSRouteImport.update({
  id: '/hitoDS',
  path: '/hitoDS',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDateRoute = WorkoutDateRouteImport.update({
  id: '/workout/$date',
  path: '/workout/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCaptureRoute = AdminCaptureRouteImport.update({
  id: '/admin/capture',
  path: '/admin/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutResultUploadRoute = ApiWorkoutResultUploadRouteImport.update({
  id: '/api/workout-result/upload',
  path: '/api/workout-result/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutResultRemoveRoute = ApiWorkoutResultRemoveRouteImport.update({
  id: '/api/workout-result/remove',
  path: '/api/workout-result/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAvatarUploadRoute = ApiProfileAvatarUploadRouteImport.update({
  id: '/api/profile-avatar/upload',
  path: '/api/profile-avatar/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanExportRoute = ApiPlanExportRouteImport.update({
  id: '/api/plan/export',
  path: '/api/plan/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLocalLoginRoute = ApiAuthLocalLoginRouteImport.update({
  id: '/api/auth/local-login',
  path: '/api/auth/local-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfirmRoute = ApiAuthConfirmRouteImport.update({
  id: '/api/auth/confirm',
  path: '/api/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthLoginRoute = ApiAdminAuthLoginRouteImport.update({
  id: '/api/admin/auth/login',
  path: '/api/admin/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/changelog': typeof ChangelogRoute
  '/hitoDS': typeof HitoDSRoute
  '/hub': typeof HubRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/capture': typeof AdminCaptureRoute
  '/admin/login': typeof AdminLoginRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/plan/export': typeof ApiPlanExportRoute
  '/api/profile-avatar/upload': typeof ApiProfileAvatarUploadRoute
  '/api/workout-result/remove': typeof ApiWorkoutResultRemoveRoute
  '/api/workout-result/upload': typeof ApiWorkoutResultUploadRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/changelog': typeof ChangelogRoute
  '/hitoDS': typeof HitoDSRoute
  '/hub': typeof HubRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/capture': typeof AdminCaptureRoute
  '/admin/login': typeof AdminLoginRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/plan/export': typeof ApiPlanExportRoute
  '/api/profile-avatar/upload': typeof ApiProfileAvatarUploadRoute
  '/api/workout-result/remove': typeof ApiWorkoutResultRemoveRoute
  '/api/workout-result/upload': typeof ApiWorkoutResultUploadRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/changelog': typeof ChangelogRoute
  '/hitoDS': typeof HitoDSRoute
  '/hub': typeof HubRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/capture': typeof AdminCaptureRoute
  '/admin/login': typeof AdminLoginRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/plan/export': typeof ApiPlanExportRoute
  '/api/profile-avatar/upload': typeof ApiProfileAvatarUploadRoute
  '/api/workout-result/remove': typeof ApiWorkoutResultRemoveRoute
  '/api/workout-result/upload': typeof ApiWorkoutResultUploadRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/body'
    | '/changelog'
    | '/hitoDS'
    | '/hub'
    | '/integrations'
    | '/login'
    | '/progress'
    | '/settings'
    | '/admin/analytics'
    | '/admin/capture'
    | '/admin/login'
    | '/workout/$date'
    | '/api/auth/confirm'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/plan/export'
    | '/api/profile-avatar/upload'
    | '/api/workout-result/remove'
    | '/api/workout-result/upload'
    | '/api/admin/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/body'
    | '/changelog'
    | '/hitoDS'
    | '/hub'
    | '/integrations'
    | '/login'
    | '/progress'
    | '/settings'
    | '/admin/analytics'
    | '/admin/capture'
    | '/admin/login'
    | '/workout/$date'
    | '/api/auth/confirm'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/plan/export'
    | '/api/profile-avatar/upload'
    | '/api/workout-result/remove'
    | '/api/workout-result/upload'
    | '/api/admin/auth/login'
  id:
    | '__root__'
    | '/'
    | '/body'
    | '/changelog'
    | '/hitoDS'
    | '/hub'
    | '/integrations'
    | '/login'
    | '/progress'
    | '/settings'
    | '/admin/analytics'
    | '/admin/capture'
    | '/admin/login'
    | '/workout/$date'
    | '/api/auth/confirm'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/plan/export'
    | '/api/profile-avatar/upload'
    | '/api/workout-result/remove'
    | '/api/workout-result/upload'
    | '/api/admin/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyRoute: typeof BodyRoute
  ChangelogRoute: typeof ChangelogRoute
  HitoDSRoute: typeof HitoDSRoute
  HubRoute: typeof HubRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCaptureRoute: typeof AdminCaptureRoute
  AdminLoginRoute: typeof AdminLoginRoute
  WorkoutDateRoute: typeof WorkoutDateRoute
  ApiAuthConfirmRoute: typeof ApiAuthConfirmRoute
  ApiAuthLocalLoginRoute: typeof ApiAuthLocalLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiPlanExportRoute: typeof ApiPlanExportRoute
  ApiProfileAvatarUploadRoute: typeof ApiProfileAvatarUploadRoute
  ApiWorkoutResultRemoveRoute: typeof ApiWorkoutResultRemoveRoute
  ApiWorkoutResultUploadRoute: typeof ApiWorkoutResultUploadRoute
  ApiAdminAuthLoginRoute: typeof ApiAdminAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitoDS': {
      id: '/hitoDS'
      path: '/hitoDS'
      fullPath: '/hitoDS'
      preLoaderRoute: typeof HitoDSRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$date': {
      id: '/workout/$date'
      path: '/workout/$date'
      fullPath: '/workout/$date'
      preLoaderRoute: typeof WorkoutDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/capture': {
      id: '/admin/capture'
      path: '/admin/capture'
      fullPath: '/admin/capture'
      preLoaderRoute: typeof AdminCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout-result/upload': {
      id: '/api/workout-result/upload'
      path: '/api/workout-result/upload'
      fullPath: '/api/workout-result/upload'
      preLoaderRoute: typeof ApiWorkoutResultUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout-result/remove': {
      id: '/api/workout-result/remove'
      path: '/api/workout-result/remove'
      fullPath: '/api/workout-result/remove'
      preLoaderRoute: typeof ApiWorkoutResultRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-avatar/upload': {
      id: '/api/profile-avatar/upload'
      path: '/api/profile-avatar/upload'
      fullPath: '/api/profile-avatar/upload'
      preLoaderRoute: typeof ApiProfileAvatarUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan/export': {
      id: '/api/plan/export'
      path: '/api/plan/export'
      fullPath: '/api/plan/export'
      preLoaderRoute: typeof ApiPlanExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/local-login': {
      id: '/api/auth/local-login'
      path: '/api/auth/local-login'
      fullPath: '/api/auth/local-login'
      preLoaderRoute: typeof ApiAuthLocalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/confirm': {
      id: '/api/auth/confirm'
      path: '/api/auth/confirm'
      fullPath: '/api/auth/confirm'
      preLoaderRoute: typeof ApiAuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/login': {
      id: '/api/admin/auth/login'
      path: '/api/admin/auth/login'
      fullPath: '/api/admin/auth/login'
      preLoaderRoute: typeof ApiAdminAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyRoute: BodyRoute,
  ChangelogRoute: ChangelogRoute,
  HitoDSRoute: HitoDSRoute,
  HubRoute: HubRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCaptureRoute: AdminCaptureRoute,
  AdminLoginRoute: AdminLoginRoute,
  WorkoutDateRoute: WorkoutDateRoute,
  ApiAuthConfirmRoute: ApiAuthConfirmRoute,
  ApiAuthLocalLoginRoute: ApiAuthLocalLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiPlanExportRoute: ApiPlanExportRoute,
  ApiProfileAvatarUploadRoute: ApiProfileAvatarUploadRoute,
  ApiWorkoutResultRemoveRoute: ApiWorkoutResultRemoveRoute,
  ApiWorkoutResultUploadRoute: ApiWorkoutResultUploadRoute,
  ApiAdminAuthLoginRoute: ApiAdminAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
