/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HitoDSRouteImport } from './routes/hitoDS'
import { Route as BodyRouteImport } from './routes/body'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutDateRouteImport } from './routes/workout.$date'
import { Route as ApiWorkoutResultUploadRouteImport } from './routes/api.workout-result.upload'
import { Route as ApiWorkoutResultRemoveRouteImport } from './routes/api.workout-result.remove'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLocalLoginRouteImport } from './routes/api.auth.local-login'
import { Route as ApiAuthConfirmRouteImport } from './routes/api.auth.confirm'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HitoDSRoute = HitoDSRouteImport.update({
  id: '/hitoDS',
  path: '/hitoDS',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDateRoute = WorkoutDateRouteImport.update({
  id: '/workout/$date',
  path: '/workout/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutResultUploadRoute = ApiWorkoutResultUploadRouteImport.update({
  id: '/api/workout-result/upload',
  path: '/api/workout-result/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutResultRemoveRoute = ApiWorkoutResultRemoveRouteImport.update({
  id: '/api/workout-result/remove',
  path: '/api/workout-result/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLocalLoginRoute = ApiAuthLocalLoginRouteImport.update({
  id: '/api/auth/local-login',
  path: '/api/auth/local-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfirmRoute = ApiAuthConfirmRouteImport.update({
  id: '/api/auth/confirm',
  path: '/api/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/hitoDS': typeof HitoDSRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/workout-result/remove': typeof ApiWorkoutResultRemoveRoute
  '/api/workout-result/upload': typeof ApiWorkoutResultUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/hitoDS': typeof HitoDSRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/workout-result/remove': typeof ApiWorkoutResultRemoveRoute
  '/api/workout-result/upload': typeof ApiWorkoutResultUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/hitoDS': typeof HitoDSRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/workout/$date': typeof WorkoutDateRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/local-login': typeof ApiAuthLocalLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/workout-result/remove': typeof ApiWorkoutResultRemoveRoute
  '/api/workout-result/upload': typeof ApiWorkoutResultUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/body'
    | '/hitoDS'
    | '/integrations'
    | '/login'
    | '/progress'
    | '/workout/$date'
    | '/api/auth/confirm'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/workout-result/remove'
    | '/api/workout-result/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/body'
    | '/hitoDS'
    | '/integrations'
    | '/login'
    | '/progress'
    | '/workout/$date'
    | '/api/auth/confirm'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/workout-result/remove'
    | '/api/workout-result/upload'
  id:
    | '__root__'
    | '/'
    | '/body'
    | '/hitoDS'
    | '/integrations'
    | '/login'
    | '/progress'
    | '/workout/$date'
    | '/api/auth/confirm'
    | '/api/auth/local-login'
    | '/api/auth/logout'
    | '/api/workout-result/remove'
    | '/api/workout-result/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyRoute: typeof BodyRoute
  HitoDSRoute: typeof HitoDSRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  WorkoutDateRoute: typeof WorkoutDateRoute
  ApiAuthConfirmRoute: typeof ApiAuthConfirmRoute
  ApiAuthLocalLoginRoute: typeof ApiAuthLocalLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiWorkoutResultRemoveRoute: typeof ApiWorkoutResultRemoveRoute
  ApiWorkoutResultUploadRoute: typeof ApiWorkoutResultUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitoDS': {
      id: '/hitoDS'
      path: '/hitoDS'
      fullPath: '/hitoDS'
      preLoaderRoute: typeof HitoDSRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$date': {
      id: '/workout/$date'
      path: '/workout/$date'
      fullPath: '/workout/$date'
      preLoaderRoute: typeof WorkoutDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout-result/upload': {
      id: '/api/workout-result/upload'
      path: '/api/workout-result/upload'
      fullPath: '/api/workout-result/upload'
      preLoaderRoute: typeof ApiWorkoutResultUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout-result/remove': {
      id: '/api/workout-result/remove'
      path: '/api/workout-result/remove'
      fullPath: '/api/workout-result/remove'
      preLoaderRoute: typeof ApiWorkoutResultRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/local-login': {
      id: '/api/auth/local-login'
      path: '/api/auth/local-login'
      fullPath: '/api/auth/local-login'
      preLoaderRoute: typeof ApiAuthLocalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/confirm': {
      id: '/api/auth/confirm'
      path: '/api/auth/confirm'
      fullPath: '/api/auth/confirm'
      preLoaderRoute: typeof ApiAuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyRoute: BodyRoute,
  HitoDSRoute: HitoDSRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  WorkoutDateRoute: WorkoutDateRoute,
  ApiAuthConfirmRoute: ApiAuthConfirmRoute,
  ApiAuthLocalLoginRoute: ApiAuthLocalLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiWorkoutResultRemoveRoute: ApiWorkoutResultRemoveRoute,
  ApiWorkoutResultUploadRoute: ApiWorkoutResultUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
